redbean_prefix: Pizza\Model\

locale: fr
full_locale: fr_FR.UTF8
timezone: Europe/Paris

title: Patchwork
description: '#PHP 5.4+ web framework powered by #Composer #Silex #RedBean #NPM'

admin_root: pizza.list
admin_user: pizza
admin_pass: admin