imports: [{ resource: common.yml }]

redbean:
    database: mysql:host=localhost;dbname=pizza
    username: pizza
    password: admin

admin:
    username: pizza
    password: admin

log_level: warning
